### ISSUE TITLE
Limit performance impact by restricting Javascript sniffing/parsing to "script" destinations

### ISSUE THREAD

**Issue by anforowicz** [annevk/orb#25]
One performance improvement idea proposed by @MattMenke2 is to exit early (blocking the response) and avoid Javascript sniffing/parsing for responses that are not for script-like destinations.

This seems like a correct optimization from security and compatibility perspectives.  I am not aware of any other destinations that would be able to consume `no-cors` Javascript.

It seems like a promising optimization from performance perspective.  ORB telemetry from Chrome M90 shows that Javascript parsing might be *potentially* needed for
- Script destinations: 24% - 31% (Javascript sniffing seems unavoidable here)
- Image destinations: 30% - 37% (ORB image sniffing and 404 / non-200 status recognition should help;  therefore looking at destination might not be necessary here)
- Empty destination: 36% - 44% (not yet understood what scenarios lead to such telemetry results;  avoiding Javascript parsing in such cases could help performance)

If we decide to implement the destination-based performance optimization, then we could add an extra step to the algorithm in the spec:

    11. If mimeType's essence starts with "audio/", "image/", or "video/", then return false.
    12. NEW STEP:
            If request's [destination](https://fetch.spec.whatwg.org/#concept-request-destination)
            is *not* [script-like](https://fetch.spec.whatwg.org/#request-destination-script-like),
            then return false.
    13. If response's body parses as JavaScript and does not parse as JSON, then return true.
    14. Return false.

**Comment by annevk** [comment]
The problem with this are service workers (which could be why you are seeing empty) caching things, which is why I have not done this. I suppose we could still use it, but unless we are okay with breaking service workers scenarios it would seem to me that any such filtering would have to allow the empty string as well. (Even that would break some edge case service worker scenarios, e.g., fetching through `<img>` and then serving the response to `<script>`, but that seems okay.)

(Note also that a 404 that is an actual image will be displayed today. That should probably not change.)

cc @jakearchibald

**Comment by jakearchibald** [comment]
Someone would need to look at how much no-cors JS is fetched in a service worker without a destination. As @annevk says, this is most likely to happen during 'install'. It's opt-in (the developer would need to specify 'no-cors'), but it might have significant use.

The popularity of modules, which require CORS, may make this number go down over time.

**Comment by annevk** [comment]
Closing this for now as it's not clear we can make a meaningful change here.
